models/Item.py
from sqlalchemy.dialects.postgresql import UUID
from flask_sqlalchemy import SQLAlchemy
import uuid

from db import db 

class Item(db.Model):
    __tablename__ = 'item'

    id = db.Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name = db.Column(db.String(256), nullable = False)
    type = db.Column(db.String(256), nullable = False)
    stock = db.Column(db.Integer(), nullable = False)
    description = db.Column(db.String(256), nullable = False)
    date = db.Column(db.DateTime(), nullable= False)

    def __repr__(self):
        return f"<Item {self.name}"

    @property
    def serialize(self):
        return {
            'id': self.id,
            'name': self.name,
            'type': self.type,
            'stock': self.stock,
            'description': self.description,
            'date': self.date
        }

app.py
from flask import Flask, request, jsonify, Response, make_response, render_template
from config import Config
from db import db
from routes.itemBlueprint import itemBp
from sqlalchemy import desc

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI']=Config.DATABASE_URI
app.config['SQLALCHEMY_TRACK_MODIFICATIONS']=False
db.init_app(app)

# Import the models (must be done after initializing the app)
from models.Item import Item

with app.app_context():
    db.create_all()
    db.session.commit()

# Register a root route
@app.route("/", methods=["get"])
def home():
    items = Item.query.order_by(desc(Item.date)).all()
    return render_template('home.html', items=items)

# Register the item routes as /item/*
app.register_blueprint(itemBp, url_prefix="/item")

# Start the app
if __name__ == "__main__":
    app.run(host='0.0.0.0', debug=True)

controllers/itemController.py
from flask import Blueprint, request, render_template, \
                  flash, g, session, redirect, url_for, \
                make_response
from io import StringIO
import csv

from models.Item import Item
from flask_sqlalchemy import SQLAlchemy
from flask import jsonify
import datetime
from db import db

# POST /item/create
def create():
    # data = request.json
    data = request.form
    print(data)
    item = Item(
        name = data.get("name", ""),
        type = data.get("type", ""),
        stock = data.get("stock", 0),
        description = data.get("description", ""),
        date = datetime.datetime.now()
    )
    db.session.add(item)
    db.session.commit()
    # return f"Successfully created item {item.id}"
    return redirect(url_for("home"))

# DELETE /item/delete
# Delete an item by id
def delete(itemId):
    item = Item.query.get_or_404(itemId)
    db.session.delete(item)
    db.session.commit()
    return redirect(url_for('home'))

# PATCH /item/update
# Update an item by id
def update(itemId):
    print("REQ IS", request)
    data = request.form
    print("dat is", data)
    item = Item.query.get_or_404(itemId)
    for key in data.keys():
        setattr(item, key, data[key] if key in data else getattr(item, key))
    db.session.commit()
    return redirect(url_for('home'))

# GET /item/list
# List all items
# Response is an array of json serialized rows
def list():
    result = Item.query.order_by(Item.date).all()
    resultJson = [x.serialize for x in result]
    return jsonify(resultJson)

# Extra feature:
# GET /item/export
# Export the table as a csv
def export():
    io = StringIO()
    cw = csv.writer(io)
    query = Item.query.order_by(Item.date).all()

    # Write the column names
    cw.writerow([x for x in query[0].serialize.keys()])

    for book in query:
        "dat is"
        cw.writerow([str(x) for x in book.serialize.values()])
    #     cw.writerows(str(x) for x in book.serialize.values())
    output = make_response(io.getvalue())
    output.headers["Content-Disposition"] = "attachment; filename=export.csv"
    output.headers["Content-type"] = "text/csv"
    return output

routes/itemBlueprint.py
from flask import Blueprint
from controllers.itemController import create, delete, list, update, export


itemBp = Blueprint('item', __name__, url_prefix='/item')

itemBp.route('/create', methods=['POST'])(create)
itemBp.route('/delete/<string:itemId>', methods=['POST'])(delete)
itemBp.route('/list', methods=['GET'])(list)
itemBp.route('/update/<string:itemId>', methods=['POST'])(update)
itemBp.route('/export', methods=['GET'])(export)

templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Shopify Backend Challenge</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>

    <div class="container">


        <br>
        <h1>Inventory System</h1>
        <p>This inventory system was built with Flask backend, a PostgreSQL database, and SQLAlchemy ORM.</p>

        <div class="row">
            <div class="col-sm-8">
                <button class="btn btn-primary btn-block" data-toggle="modal" data-target="#createModal">Create Item</button>
            </div>
            <!-- Modal -->
            <div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="createModalLabel"
                aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <form id="editItem" method="post" action={{ url_for('item.create')}}>
                            <div class="modal-header">
                                <h5 class="modal-title">Modal title</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                            <div class="modal-body">
                                <div class="form-group">
                                    <label for="name">Name</label>
                                    <input type="text" class="form-control" id="name" name="name" value="Apple">
                                </div>
                                <div class="form-group">
                                    <label for="type">Category</label>
                                    <select class="form-control" name="type" id="type">
                                        <option value="Food" selected>Food</option>
                                        <option value="Clothing">Clothing</option>
                                        <option value="Electronics">Electronics</option>
                                      </select>
                                  </div>
                                <div class="form-group">
                                    <label for="name">Description</label>
                                    <input type="text" class="form-control" id="description" name="description"
                                        value="">
                                </div>
                                <div class="form-group">
                                    <label for="stock">Stock</label>
                                    <input type="number" class="form-control" id="stock" name="stock" min=0
                                        value="1">
                                </div>


                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>

                    </div>
                    </form>

                </div>
            </div>
            <div class="col-sm-4">
                <a href="/item/export"><button class="btn btn-success btn-block">Export to CSV</button></a>

            </div>
        </div>
        <br>
        <p>Current items in inventory database:</p>

        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Category</th>
                    <th>Description</th>
                    <th>Stock</th>
                    <th>Date added</th>

                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for item in items %}
                <tr>
                    <!-- Show data -->
                    <td>{{item.name}}</td>
                    <td>{{item.type}}</td>
                    <td>{{item.description}}</td>
                    <td>{{item.stock}}</td>
                    <td>{{item.date.strftime('%Y-%m-%d %H:%M:%S')}}</td>

                    <td>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target={{"#exampleModal"+item.id|string}}>
                            Edit
                        </button>
                        <!-- Modal -->
                        <div class="modal fade" id={{"exampleModal"+item.id|string}} tabindex="-1" role="dialog"
                            aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <form id="editItem" method="post" action={{ url_for('item.update', itemId=item.id)
                                        }}>

                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Edit item</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>

                                        <div class="modal-body">
                                            <div class="form-group">
                                                <label for="name">New name</label>
                                                <input type="text" class="form-control" id="name" name="name"
                                                    value="{{item.name}}">
                                            </div>
                                            <div class="form-group">
                                                <label for="type">Category</label>
                                                <select class="form-control" name="type" id="type">
                                                    <option value="Food" {% if item.type == "Food" %} selected {% endif %}>Food</option>
                                                    <option value="Clothing"  {% if item.type == "Clothing" %} selected {% endif %}>Clothing</option>
                                                    <option value="Electronics"  {% if item.type == "Electronics" %} selected {% endif %}>Electronics</option>
                                                  </select>
                                              </div>
                                            
                                            <div class="form-group">
                                                <label for="name">Description</label>
                                                <input type="text" class="form-control" id="description"
                                                    name="description" value="{{item.description}}">
                                            </div>
                                            <div class="form-group">
                                                <label for="stock">Stock</label>
                                                <input type="number" class="form-control" id="stock" name="stock" min=0
                                                    value="{{item.stock}}">
                                            </div>


                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary"
                                                data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-primary">Submit</button>
                                        </div>

                                </div>
                                </form>

                            </div>
                        </div>

                        <!-- <form method="post" action={{ url_for('item.delete', itemId=item.id) }}>
                    <input class="btn" type="submit" name="delete" value="Edit">
                </form> -->
                    </td>
                    <!-- Delete button -->
                    <td>
                        <form method="post" action={{ url_for('item.delete', itemId=item.id) }}>
                            <input class="btn btn-danger" type="submit" name="delete" value="Delete">
                        </form>
                    </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>

</html>